# Introduction to Pytorch 1.0

## Author: Niranjan Kumar
* **References: The code in this notebook is taken from the deep learning course by [PadhAI](https://padhai.onefourthlabs.in/).**
* **Github Repo: https://github.com/Niranjankumar-c/DeepLearning-PadhAI**
* **Medium blog post: [Getting Started With Pytorch In Google Collab With Free GPU](https://hackernoon.com/getting-started-with-pytorch-in-google-collab-with-free-gpu-61a5c70b86a/)**


![alt text](https://code.fb.com/wp-content/uploads/2018/09/PyTorch_Blog-Post_Hero.png)

# Outline
* PyTorch
* What are tensors
* Initialising, slicing, reshaping tensors
* Numpy and PyTorch interfacing
* GPU support for PyTorch + Enabling GPUs on Google Colab
* Speed comparisons, Numpy -- PyTorch -- PyTorch on GPU
* Autodiff concepts and application
* Writing a basic learning loop using autograd
* Conclusion

In [0]:
#import libraries
import torch
import numpy as np
import matplotlib.pyplot as plt

In [69]:
torch.__version__

'1.1.0'

# Initialise tensors

In [70]:
x = torch.ones(3,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [71]:
x = torch.ones(3, 2)
print(x)
x = torch.zeros(3, 2)
print(x)
x = torch.rand(3, 2)
print(x)
x = torch.randn(3,3)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.0190, 0.7368],
        [0.6252, 0.7905],
        [0.4517, 0.4048]])
tensor([[ 0.0547, -1.9015, -1.1462],
        [ 0.3982, -1.2941,  0.8751],
        [ 0.8588, -0.8963,  1.3100]])


In [72]:
x = torch.empty(3, 2)
print(x)

tensor([[3.0467e-37, 0.0000e+00],
        [4.4842e-44, 0.0000e+00],
        [       nan, 0.0000e+00]])


In [73]:
x = torch.empty(3, 2)
print(x)
y = torch.zeros_like(x)
print(y)

tensor([[-8.4230e-21,  0.0000e+00],
        [ 4.4842e-44,  0.0000e+00],
        [        nan,  0.0000e+00]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [74]:
x = torch.linspace(0 , 1, steps = 5)
print(x)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [75]:
x = torch.tensor([[1, 2], 
                 [3, 4], 
                 [5, 6]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


# Slicing tensors

In [76]:
print(x.size())
print(x[:, 1])
print(x[0, :])

torch.Size([3, 2])
tensor([2, 4, 6])
tensor([1, 2])


In [77]:
y = x[1, 1]
print(y)
print(y.item())

tensor(4)
4


# Reshaping tensors

In [78]:
print(x)
y = x.view(2, 3)
print(y)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [79]:
y = x.view(6,-1) 
print(y)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


# Simple Tensor Operations

In [80]:
x = torch.ones([3, 2])
y = torch.ones([3, 2])
z = x + y
print(z)
z = x - y
print(z)
z = x * y
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [81]:
torch.sub(x,y)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [82]:
z = y.add(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [83]:
z = y.add_(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


# Numpy <> PyTorch

In [84]:
x_np = x.numpy()
print(type(x), type(x_np))
print(x_np)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [85]:
a = np.random.randn(5)
print(a)
a_pt = torch.from_numpy(a)
print(type(a), type(a_pt))
print(a_pt)

[ 0.84776428  0.77146184 -0.83965444  0.13617828 -0.34339054]
<class 'numpy.ndarray'> <class 'torch.Tensor'>
tensor([ 0.8478,  0.7715, -0.8397,  0.1362, -0.3434], dtype=torch.float64)


In [86]:
np.add(a, 1, out=a)
print(a)
print(a_pt) 

[1.84776428 1.77146184 0.16034556 1.13617828 0.65660946]
tensor([1.8478, 1.7715, 0.1603, 1.1362, 0.6566], dtype=torch.float64)


In [87]:
%%time
for i in range(100):
    a = np.random.randn(100,100)
    b = np.random.randn(100,100)
    c = np.matmul(a, b)

CPU times: user 170 ms, sys: 105 ms, total: 275 ms
Wall time: 200 ms


In [88]:
%%time
for i in range(100):
    a = torch.randn([100, 100])
    b = torch.randn([100, 100])
    c = torch.matmul(a, b)

CPU times: user 60.5 ms, sys: 39 ms, total: 99.6 ms
Wall time: 60.9 ms


In [89]:
%%time
for i in range(10):
    a = np.random.randn(10000,10000)
    b = np.random.randn(10000,10000)
    c = a + b

CPU times: user 1min 32s, sys: 160 ms, total: 1min 32s
Wall time: 1min 32s


In [90]:
%%time
for i in range(10):
    a = torch.randn([10000, 10000])
    b = torch.randn([10000, 10000])
    c = a + b

CPU times: user 24.9 s, sys: 100 ms, total: 25 s
Wall time: 25 s


# CUDA support

In [91]:
print(torch.cuda.device_count())

1


In [92]:
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))

Tesla K80


In [0]:
#assign to a variable
cuda0 = torch.device('cuda:0')

In [94]:
a = torch.ones(3, 2, device=cuda0)
b = torch.ones(3, 2, device=cuda0)
c = a + b
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], device='cuda:0')


In [0]:
c = c.cpu()

In [96]:
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [97]:
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], device='cuda:0')


# Speed Comparision Numpy vs Pytorch

In [98]:
%%time
for i in range(10):
    a = np.random.randn(10000,10000)
    b = np.random.randn(10000,10000)
    np.add(b, a)

CPU times: user 1min 32s, sys: 153 ms, total: 1min 32s
Wall time: 1min 32s


In [99]:
%%time
for i in range(10):
    a_cpu = torch.randn([10000, 10000])
    b_cpu = torch.randn([10000, 10000])
    b_cpu.add_(a_cpu)

CPU times: user 24.4 s, sys: 62 ms, total: 24.4 s
Wall time: 24.4 s


In [100]:
%%time
for i in range(10):
    a = torch.randn([10000, 10000], device=cuda0)
    b = torch.randn([10000, 10000], device=cuda0)
    b.add_(a)

CPU times: user 662 µs, sys: 13 ms, total: 13.7 ms
Wall time: 15.2 ms


In [101]:
%%time
for i in range(10):
    a = np.random.randn(10000,10000)
    b = np.random.randn(10000,10000)
    np.matmul(b, a)

CPU times: user 24min 22s, sys: 14.4 s, total: 24min 37s
Wall time: 13min 15s


In [102]:
%%time
for i in range(10):
    a_cpu = torch.randn([10000, 10000])
    b_cpu = torch.randn([10000, 10000])
    torch.matmul(a_cpu, b_cpu)

CPU times: user 4min 51s, sys: 336 ms, total: 4min 51s
Wall time: 4min 51s


In [103]:
%%time
for i in range(10):
    a = torch.randn([10000, 10000], device=cuda0)
    b = torch.randn([10000, 10000], device=cuda0)
    torch.matmul(a, b)

CPU times: user 20.1 ms, sys: 28 ms, total: 48.1 ms
Wall time: 53.7 ms


# Autodiff

In [104]:
x = torch.ones([3,2], requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [105]:
y = x + 5
print(y)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [106]:
z = y*y + 1
print(z)

tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)


In [107]:
t = torch.sum(z)
print(t)

tensor(222., grad_fn=<SumBackward0>)


In [0]:
t.backward()

In [109]:
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


# $t = \sum_i z_i, z_i = y_i^2 + 1, y_i = x_i + 5$

# $\frac{\partial t}{\partial x_i} = \frac{\partial z_i}{\partial x_i} = \frac{\partial z_i}{\partial y_i} \frac{\partial y_i}{\partial x_i} = 2y_i \times 1$


# At x = 1, y = 6, $\frac{\partial t}{\partial x_i} = 12$

## Second Example - Auto Diff

In [110]:
#second example
x = torch.ones([3, 2], requires_grad=True)
y = x + 5
r = 1/(1 + torch.exp(-y))
print(r)
s = torch.sum(r)
s.backward()
print(x.grad)

tensor([[0.9975, 0.9975],
        [0.9975, 0.9975],
        [0.9975, 0.9975]], grad_fn=<MulBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


In [111]:
x = torch.ones([3, 2], requires_grad=True)
y = x + 5
r = 1/(1 + torch.exp(-y))
a = torch.ones([3, 2])
r.backward(a)
print(x.grad)

tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


$\frac{\partial{s}}{\partial{x}} = \frac{\partial{s}}{\partial{r}} \cdot \frac{\partial{r}}{\partial{x}}$

For the above code $a$ represents $\frac{\partial{s}}{\partial{r}}$ and then $x.grad$ gives directly $\frac{\partial{s}}{\partial{x}}$



# Autodiff example that looks like what we have been doing

In [0]:
x = torch.randn([20, 1], requires_grad=True)
y = 3*x - 2

In [0]:
w = torch.tensor([1.], requires_grad = True)
b = torch.tensor([1.], requires_grad = True)
y_hat = w * x + b
loss = torch.sum((y_hat - y)**2)

In [114]:
print(loss)

tensor(230.5582, grad_fn=<SumBackward0>)


In [0]:
loss.backward()

In [116]:
print(w.grad, b.grad)

tensor([-59.6847]) tensor([113.9157])


# Do it in a loop

In [117]:
learning_rate = 0.01

w = torch.tensor([1.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)

print(w.item(), b.item())

for i in range(10):
    x = torch.randn([20, 1])
    y = 3*x - 2
  
    y_hat = w*x + b
    loss = torch.sum((y_hat - y)**2)
  
    loss.backward()
  
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
    
    w.grad.zero_()
    b.grad.zero_()

print(w.item(), b.item())  

1.0 1.0
1.8029184341430664 -0.2683265209197998
2.6225297451019287 -1.0458576679229736
2.8130393028259277 -1.419053316116333
2.812117338180542 -1.6180460453033447
2.9704225063323975 -1.8063768148422241
2.974210023880005 -1.8826671838760376
2.969771146774292 -1.9270395040512085
2.9817845821380615 -1.956540584564209
2.989637613296509 -1.9740781784057617
2.9960341453552246 -1.9859132766723633


# Do it for a large problem

In [119]:
%%time
learning_rate = 0.001
N = 10000000
epochs = 200

w = torch.rand([N], requires_grad=True, device=cuda0)
b = torch.ones([1], requires_grad=True, device=cuda0)

# print(torch.mean(w).item(), b.item())

for i in range(epochs):  
    x = torch.randn([N], device=cuda0)
    y = torch.dot(3*torch.ones([N], device=cuda0), x) - 2
  
    y_hat = torch.dot(w, x) + b
    loss = torch.sum((y_hat - y)**2)
  
    loss.backward()
  
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
    
    w.grad.zero_()
    b.grad.zero_()

print(torch.mean(w).item(), b.item())  

nan nan
CPU times: user 891 ms, sys: 623 ms, total: 1.51 s
Wall time: 1.54 s


# Conclusion
* In this notebook, we briefly looked at the Pytorch & Google Colab and we also saw how to enable GPU hardware accelerator in Colab.
* Then we have seen how to create tensors in Pytorch and perform some basic operations on those tensors by utilizing CUDA supported GPU. 
* After that, we discussed the Pytorch autograd package which gives us the ability to perform automatic gradient computation on tensors by taking a simple example.

## Contact Me

* Linkedln: https://linkedin.com/in/niranjankumar-c/
* GitHub: https://github.com/niranjankumar-c/
* Twitter: https://twitter.com/Nkumar_n
* Medium: https://medium.com/@niranjankumarc/



